### ISSUE TITLE
Suggested topics

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/CS101#4]
Please add topics here that you think we should have workshops on!

**Comment by afloresescarcega** [comment]
In general, devops. 

- [ ]  setting up an ec2 instance
- [ ]  creating and uploading docker images
- [ ]  Shell scripting
- [ ]  Compiling c code and debugging with GDB
-[ ]   SQL querying
-[ ]  how to prepare and perform well in hackathons
-[ ]  using regular expressions
-[ ] typesetting in latex

**Comment by alex-bellon** [comment]
### Already in curriculum:
- Shell scripting 
   - One of the 'extra' topics
- Compiling c code and debugging with GDB 
   - One of the 'advanced' topics

### Things that students wouldn't necessarily encounter during intro classes:
- SQL querying 
- Setting up an ec2 instance
- Setting up Jenkins CI/CD or learning how to use GitLab’s

### Not technical skills, but could be incoporated into some other event:
- How to prepare and perform well in hackathons

### Things to add to curriculum:

- Using regular expressions
   - Maybe add to the editors advanced talk? Or make it its own
- Typesetting in latex
   - Again, maybe add to editors advanced talk
- Creating and uploading docker images
   - Maybe not this exactly, but general docker/container things could be added as an 'extra' topic

**Comment by ChiaHuaLu** [comment]
Just some of my opinions regarding Alex's suggestions:
- Setting EC2 and Jenkins CI/CD is what Cloud and MWA is about, I don't think we should teach that in detail.
- Downing's SWE goes into depth of regex and SQL
- Don't really think Latex is that useful or required in CS. Maybe a low priority topic?
- Classes don't really teach Docker, that would be a good topic to go into
- C and gdb is good at end of semesters to prepare for incoming CS429 kids
